CREATE SCHEMA IF NOT EXISTS tracker;

CREATE TABLE IF NOT EXISTS tracker.patients (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    surname VARCHAR(100) NOT NULL,
    patronymic VARCHAR(100),
    birthday DATE NOT NULL,
    email VARCHAR(254) NOT NULL,
    phone_number VARCHAR(12) NOT NULL,
    oms VARCHAR(16) NOT NULL UNIQUE,
    sex VARCHAR(20) NOT NULL,
    height INTEGER NOT NULL CHECK (height BETWEEN 30 AND 250)
);

CREATE TABLE IF NOT EXISTS tracker.patient_login (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oms VARCHAR(16) NOT NULL UNIQUE REFERENCES tracker.patients (oms) ON DELETE CASCADE,
    password VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS tracker.doctors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    surname VARCHAR(100) NOT NULL,
    personnel_number VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS tracker.doctor_login (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personnel_number VARCHAR(50) NOT NULL UNIQUE
        REFERENCES tracker.doctors (personnel_number) ON DELETE CASCADE,
    password VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS tracker.attacks_of_illness (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INTEGER NOT NULL REFERENCES tracker.patients (id) ON DELETE CASCADE,
    date_time TIMESTAMP NOT NULL,
    scale INTEGER NOT NULL CHECK (scale BETWEEN 1 AND 5)
);

CREATE TABLE IF NOT EXISTS tracker.spirometry (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INTEGER NOT NULL REFERENCES tracker.patients (id) ON DELETE CASCADE,
    result INTEGER NOT NULL CHECK (result BETWEEN 50 AND 950),
    date_time TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS tracker.medicine (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    mkg INTEGER NOT NULL CHECK (mkg > 0),
    CONSTRAINT uq_medicine_name_dose UNIQUE (name, mkg)
);

CREATE TABLE IF NOT EXISTS tracker.medicine_to_patient (
    patient_id INTEGER NOT NULL REFERENCES tracker.patients (id) ON DELETE CASCADE,
    medicine_id INTEGER NOT NULL REFERENCES tracker.medicine (id) ON DELETE CASCADE,
    PRIMARY KEY (patient_id, medicine_id)
);

CREATE TABLE IF NOT EXISTS tracker.taking_medication (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INTEGER NOT NULL REFERENCES tracker.patients (id) ON DELETE CASCADE,
    medicine_id INTEGER NOT NULL REFERENCES tracker.medicine (id),
    date_time TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_attacks_patient_date
    ON tracker.attacks_of_illness (patient_id, date_time);
CREATE INDEX IF NOT EXISTS idx_spirometry_patient_date
    ON tracker.spirometry (patient_id, date_time);
CREATE INDEX IF NOT EXISTS idx_medication_patient_date
    ON tracker.taking_medication (patient_id, date_time);
